### PR TITLE
WIP: assigned task form (due date, computed due date, notifications)

### PR DESCRIPTION
**Pull request by garbas**
# Mockup

Mockup
# Todo

(in order)
- [x] include `plone.app.widgets` and `mockup`
- [x] create form (fields: due_date:datetime, due_date_rule:textline, notification_rules:list
- [x] tabs in edit forms are lost (add form_tabbing.js to default bundle)
- [x] style in add form is lost (probably due to some z3cform-ish IFormLayer problem)
- [x] create 2 empty patterns, one for due_date_rule and other for notification_rules, and make sure they get initialized
- [x] create z3cform widget/converters for due_date_rule and notification_rules
- [x] add invariant check for due_date and due_date_rule fields (only one is allowed)
- [x] create due_date_rule pattern (mockup) - take inspiration from querystring pattern
- [x] create notifications_list pattern, reuse due_date_rule (mockup)
- [ ] create accessor method for due date which takes into account both due_date ad due_date_rule
- [ ] timezone in "assigned form" should be a separate field like in plone.app.event (eg. due_date_timezone)
- [ ] where to store this data (attribute or annotation storage), do we need an accesor adapter?
# Questions

<no questions>

[Review on Reviewable](https://reviewable.io/reviews/upiq/uu.task/14)

### CODE REVIEW

**Comment by aclark4life** [comment]
Thanks will review and merge shortly

**Comment by garbas** [comment]
@aclark4life dont merge ... it is WIP, just put it here so you can see my progress.

**Comment by aclark4life** [comment]
@garbas Ah! Got it, thanks

**Comment by aclark4life** [comment]
Looks good, thanks
screenshot 2015-06-24 14 20 30

**Pull request merged**
